version: "3.9"

services:
  # Define service for MYSQL container
  db:
    image: mysql:5.7

    # volume mount for data persistence
    volumes:
      - db_data:/var/lib/mysql 
    restart: always
    ports:
        - '3306:3306'    

    # environement vars for mysql db
    environment:
      MYSQL_ROOT_PASSWORD: temppass
      MYSQL_DATABASE: my_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_user_temppass
    networks:
      - my_net

  # phpmyadmin container service
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: temppass
    networks:
      - my_net

networks:
    my_net:

# Will persists any updates made by wp to database.
volumes:
  db_data: {}